Revisión fn0FA - fn0FB MI Aula
Admin-EDE/DockerEdeCode pull request #6
Opened 2021-05-27 13:08 UTC by MiAulaTI

Se genera función fn0FA-0FB para validar que estudiantes tengan al menos una persona asociada y que esta ultima este autorizada para retirarlo.

Favor revisar función para validar su estructura y lógica, se tomo como referencia funciones existentes en proyecto.

2021-05-27 14:29 UTC, Admin-EDE requested changes
el archivo ede/ede/checkSQLiteEDE.py se ve ok, aunque me parece que la definición de las variables no esta funcionando. Pudiste probarlas?

por otro lado, el archivo ede/ede/ceds-nds-v7_1_encryptedD3.db no se debería haber modificado, te sugiero actualizar tu código y ocupar el archivo que tenemos disponible actualmente.

2021-05-27 14:38 UTC, MiAulaTI commented
Miguel, 

El archivo de base de datos esta modificado por que justamente tome el ultimo del repositorio Admin-EDE y lo lleve a mi repositorio para que este actualizado, recuerda que modificaste la vista personList.

Con respecto a las variables de las funciones, en realidad desconozco como probarlo, si me ayudas con eso te lo agradecería.

2021-05-27 14:58 UTC, Admin-EDE commented
Coordinemos una reunión para ver el tema de las variables. Mientras tanto por favor actualiza el archivo de la base de datos que se encuentra en conflicto.

2021-05-27 15:15 UTC, MiAulaTI commented
Base actualizada.

2021-06-25 17:08 UTC, closed without merging

2021-06-25 17:08 UTC, Admin-EDE commented
por favor usar rama dev